import type { Metadata } from "next";
import "./globals.css";
import { Instrument_Sans } from "next/font/google";

const instrument = Instrument_Sans({
	weight: ["400", "500", "600", "700"],
	subsets: ["latin"],
	display: "swap",
	variable: "--font-instrument",
});

export const metadata: Metadata = {
	title: "Link Sharing",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${instrument.variable}`}>{children}</body>
		</html>
	);
}
